name: Debug Secrets

on: workflow_dispatch  # 手動実行

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check if SSH_PRIVATE_KEY exists
        run: |
          if [[ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]]; then
            echo "❌ SSH_PRIVATE_KEY is NOT set!"
            exit 1
          else
            echo "✅ SSH_PRIVATE_KEY is set!"
          fi
      - name: Check if SSH Secrets exist
        run: |
          if [[ -z "${{ secrets.SSH_USERNAME }}" ]]; then
            echo "❌ SSH_USERNAME is NOT set!"
          else
            echo "✅ SSH_USERNAME is set!"
          fi

          if [[ -z "${{ secrets.SSH_HOST }}" ]]; then
            echo "❌ SSH_HOST is NOT set!"
          else
            echo "✅ SSH_HOST is set!"
          fi

          if [[ -z "${{ secrets.SSH_PORT }}" ]]; then
            echo "❌ SSH_PORT is NOT set!"
          else
            echo "✅ SSH_PORT is set!"
          fi
