name: Debug Secrets

on: workflow_dispatch  # 手動実行

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check if SSH_PRIVATE_KEY exists
        run: |
          if [[ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]]; then
            echo "❌ SSH_PRIVATE_KEY is NOT set!"
            exit 1
          else
            echo "✅ SSH_PRIVATE_KEY is set!"
          fi
